name: Build, Tag, and Release on Merge to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-tag-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build script to generate dist directory
      - name: Build project
        run: npm run build

      # Step 5: Set up Git user name and email
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit any uncommitted changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: commit changes before version bump" || echo "No changes to commit"

      # Step 7: Bump the version and create a tag
      - name: Bump version
        id: bump_version
        run: |
          NEW_VERSION=$(npm version patch -m "chore(release): %s")
          NEW_VERSION=${NEW_VERSION#*v}  # Remove 'v' if present
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      # Step 8: Push the changes and the new tag
      - name: Push changes and tag
        run: |
          git push origin main --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 9: Create a GitHub Release with the new tag
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
